{
    "kind": "SelfSubjectAccessReview",
    "apiVersion": "authorization.k8s.io/v1",
    "metadata": {
        "name": ""
    },
    "spec": {
        "resourceAttributes": {
            "namespace": "pytorch",
            "verb": "create",
            "group": "rbac.authorization.k8s.io",
            "resource": "rolebindings"
        }
    }
}